name: BuildBattle
main: WEATHERCRAFTYT1\BB
api: [3.0.0]
version: 1.0.0
author: WEATHERCRAFTYT1

commands:
    bb:
        usage: /bb <make>
        description: CreateGame
permissions:
    bb.op:
        default: op
  
